SET PRJ_DIR=%CD%

SET JAVA_BIN=Y:\j2sdk1.4.2\bin
SET J2ME_DIR=Y:\WTK22

SET RELEASE_DIR=_release

SET JAR_NAME=SuperMario
SET PRJ_MIDLET_NAME=Super Mario
SET MIDLET_NAME=MarioMidlet

SET VERSION=1.0.0
SET DESCRIPTION=Application for testing

SET TMPCLASSES=_tmpclasses
SET CLASSES=_classes

SET FILENAME_VER=%VERSION:.=%

SET PHONE_NAME=SonyEricssonK800
SET LANGUAGE=EN

SET OBFUSCATE=%PRJ_DIR%\_obfucates
SET PROGUARD=%PRJ_DIR%\tools\ProGuard
SET CPP=%PRJ_DIR%\tools\CPP
SET TMP_SRC=%PRJ_DIR%\_src
SET CLASSPATH=%J2ME_DIR%\lib\midpapi20.jar;%J2ME_DIR%\lib\cldcapi11.jar
SET SE_DIR=Y:\JavaME_SDK_CLDC\WTK2